services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: skillsrock_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: danik22081
    ports:
      - "5432:5432"
    networks:
      - app-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    image: parodia/testtask:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dockermvn
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/skillsrock_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=danik22081
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.yaml
      - CACHE_TIME_TO_LIVE=20
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

networks:
  app-network: